# Generated by Django 4.2.2 on 2024-09-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('organization', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('event', models.CharField(blank=True, max_length=2000, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('submitted_at',),
            },
        ),
    ]
